server:
  port: 8081

spring:
  application:
    name: coffee-member
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: kosa01
    password: 1234

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.coffeemember.vo

# eureka setting
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true